// NextDNS MCP bridge extension for the pi coding harness.
//
// Generated by `scripts/ai_e2e_harness.py` (do not edit the generated copy).
// It registers the NextDNS MCP server's grouped tools as pi tools and proxies
// every call to a live `mcp_server` subprocess over stdio (newline-delimited
// JSON-RPC 2.0, the MCP stdio transport). This is what puts an *LLM* in the
// tool-calling seat: the harness sends a task prompt to pi, pi's model decides
// which NextDNS tool to call with which arguments, and this bridge executes
// that decision against the real server.
//
// No static imports on purpose: the factory receives `pi`, so the extension
// needs no module resolution to load. Node builtins are required lazily
// inside handlers.
//
// SPDX-License-Identifier: MIT

const CONFIG = __NEXTDNS_MCP_BRIDGE_CONFIG_JSON__;

export default async function (pi: any) {
  let child: any = null;
  let buffer = "";
  let nextId = 1;
  const pending = new Map<string, (msg: any) => void>();

  function fail(err: any) {
    const msg = err && err.message ? err.message : String(err);
    for (const [id, resolve] of pending) {
      resolve({ id, error: { code: -32000, message: `bridge shut down: ${msg}` } });
    }
    pending.clear();
  }

  function ensureServer() {
    if (child) return;
    const cp = require("node:child_process");
    const cmd = CONFIG.server.command;
    const args = CONFIG.server.args || [];
    const env = Object.assign({}, process.env, CONFIG.server.env || {});
    try {
      child = cp.spawn(cmd, args, {
        cwd: CONFIG.server.cwd || undefined,
        env,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch (err) {
      child = null;
      throw err;
    }
    const onLine = (line: string) => {
      if (!line.trim()) return;
      let msg: any;
      try {
        msg = JSON.parse(line);
      } catch (_e) {
        return; // not a JSON-RPC message; ignore
      }
      if (msg && typeof msg.id !== "undefined" && (msg.result !== undefined || msg.error !== undefined)) {
        const resolve = pending.get(String(msg.id));
        if (resolve) {
          pending.delete(String(msg.id));
          resolve(msg);
        }
      }
    };
    const feed = (chunk: Buffer) => {
      buffer += chunk.toString("utf8");
      let idx: number;
      while ((idx = buffer.indexOf("\n")) >= 0) {
        const line = buffer.slice(0, idx);
        buffer = buffer.slice(idx + 1);
        onLine(line);
      }
    };
    child.stdout.on("data", feed);
    child.stderr.on("data", () => {}); // keep the actor's stdout clean
    child.on("error", (err: any) => fail(err));
    child.on("close", () => {
      child = null;
      fail(new Error("mcp server process exited"));
    });
  }

  function rpc(method: string, params: any) {
    return new Promise((resolve, reject) => {
      ensureServer();
      const id = String(nextId++);
      const timer = setTimeout(() => {
        pending.delete(id);
        reject(new Error(`mcp rpc ${method} timed out after ${CONFIG.timeout_ms || 30000}ms`));
      }, CONFIG.timeout_ms || 30000);
      pending.set(id, (msg: any) => {
        clearTimeout(timer);
        if (msg.error) reject(new Error(`${method}: ${msg.error.message || JSON.stringify(msg.error)}`));
        else resolve(msg.result);
      });
      const payload = JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n";
      try {
        child.stdin.write(payload);
      } catch (err) {
        clearTimeout(timer);
        pending.delete(id);
        reject(err);
      }
    });
  }

  let initialized = false;
  async function initServer() {
    if (initialized) return;
    await rpc("initialize", {
      protocolVersion: "2025-03-26",
      capabilities: {},
      clientInfo: { name: "nextdns-e2e-pi-bridge", version: "1.0.0" },
    });
    // MCP spec: signal readiness after the initialize response (no id).
    child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }) + "\n");
    initialized = true;
  }

  async function loadToolSchemas(): Promise<Record<string, any>> {
    await initServer();
    const res: any = await rpc("tools/list", {});
    const map: Record<string, any> = {};
    for (const t of (res && res.tools) || []) {
      if (t && t.name) map[t.name] = t;
    }
    return map;
  }

  function textOf(res: any): string {
    if (res && Array.isArray(res.content)) {
      return res.content
        .map((c: any) => (c && c.text ? c.text : ""))
        .join("")
        .slice(0, 20000);
    }
    if (res === undefined || res === null) return "";
    return String(typeof res === "string" ? res : JSON.stringify(res)).slice(0, 20000);
  }

  // Fetch the server's real tool schemas so the LLM sees the full, accurate
  // tool surface (argument names, types, enums). If the server cannot be
  // reached at startup, fall back to a permissive schema; the calls will still
  // be executed (and reported) when the server answers.
  let schemas: Record<string, any> = {};
  try {
    schemas = await loadToolSchemas();
  } catch (_e) {
    schemas = {};
  }

  for (const toolName of CONFIG.tools || []) {
    const tool = schemas[toolName];
    const description =
      (tool && tool.description) ||
      `NextDNS MCP server tool "${toolName}". Call it with JSON arguments that match the task.`;
    const parameters =
      tool && tool.inputSchema
        ? tool.inputSchema
        : {
            type: "object",
            properties: {},
            additionalProperties: true,
          };
    pi.registerTool({
      name: toolName,
      label: toolName,
      description,
      parameters,
      async execute(_toolCallId: string, params: any) {
        await initServer();
        const res: any = await rpc("tools/call", { name: toolName, arguments: params || {} });
        if (res && res.isError) {
          throw new Error(textOf(res) || `tool ${toolName} reported an error`);
        }
        return { content: [{ type: "text", text: textOf(res) || "OK" }], details: {} };
      },
    });
  }

  pi.on("session_shutdown", async () => {
    if (child) {
      try {
        child.kill();
      } catch (_e) {
        // best effort
      }
      child = null;
    }
  });
}
